AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda Ruby application
Resources:
  function:
    Type: AWS::Serverless::Function
    # 関数の定義
    Properties:
      Handler: lambda_function.LambdaFunction::Handler.process
      Runtime: ruby3.2
      Description: Ruby function
      MemorySize: 512
      Timeout: 10
      Layers:
        - !Ref libs
      Environment:
        Variables:
          GEM_HOME: /opt/vendor/bundle/ruby/3.2.0
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ruby-libs
      Description: Ruby libs
      ContentUri: ./my_ruby_package.zip
      CompatibleRuntimes:
        - ruby3.2
